apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: default
spec:
  selector:
    app: hdfs-namenode
  ports:
    - name: webhdfs
      port: 9864
      targetPort: 9864
    - name: rpc
      port: 8020
      targetPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  namespace: default
spec:
  selector:
    app: hdfs-datanode
  ports:
    - name: dn
      port: 9864
      targetPort: 9864
