apiVersion: batch/v1
kind: Job
metadata:
  name: ml-train
  namespace: default
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          image: machine-learning-model:latest
          imagePullPolicy: Never
          command: ["python", "/app/train_and_log_mlflow.py"]
          resources:
            requests:
              cpu: "1000m"
              memory: "5Gi"
            limits:
              cpu: "2000m"
              memory: "9Gi"
          env:
            - name: HDFS_WEBHDFS_URL
              value: "http://hdfs-namenode.default.svc.cluster.local:9870/webhdfs/v1"
            - name: HDFS_USER
              value: "hdfs"
            - name: HDFS_AUTOBAHN_DIR
              value: "/datalake/autobahn"
            - name: HDFS_WEATHER_DIR
              value: "/datalake/weather_hist"
            - name: HDFS_DATANODE_SERVICE
              value: "hdfs-datanode.default.svc.cluster.local:9864"
            - name: MLFLOW_TRACKING_URI
              value: "file:/mlruns"   # optional, hier explizit angegeben (vmtl. auch Standard)

          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /mlruns

      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
