apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-consumer
  template:
    metadata:
      labels:
        app: jupyter-consumer
    spec:
      containers:
        - name: jupyter-consumer
          image: jupyter-consumer:latest
          imagePullPolicy: Never

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
            - name: KAFKA_TOPIC_INPUT
              value: "weather-raw"
            - name: KAFKA_GROUP_ID
              value: "jupyter-consumer-group"

            - name: MLFLOW_TRACKING_URI
              value: "file:/mlruns"
            - name: RUN_ID_FILE
              value: "/mlruns/LATEST_RUN_ID"

            # MariaDB im Heatmap-Pod (Service folgt später)
            # Beispiel-URL (passen wir an sobald heatmap/mariadb existiert):
            - name: MARIADB_URL
              value: "mysql+pymysql://root:root@mariadb.default.svc.cluster.local:3306/predictions"

            - name: BATCH_SIZE
              value: "200"
            - name: FLUSH_SEC
              value: "5"

          resources:
            requests:
              cpu: "200m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "3Gi"

          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /mlruns

      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
