apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-train
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antoni-t/big_data_engineering_minikube.git
    targetRevision: main
    path: machine_learning_model/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}