apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-producer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antoni-t/big_data_engineering_minikube.git
    targetRevision: main
    path: weather-producer/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
